name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Spotless check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK
        uses: actions/setup-java@v3.14.1
        with:
          distribution: adopt
          java-version: 21
      - name: spotless
        run: ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy CI gradle.properties
        shell: bash
        run: |
          mkdir -p ~/.gradle
          cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21

      - uses: gradle/gradle-build-action@v3.5.0
      - name: Make Gradle executable
        run: chmod +x ./gradlew