# スクリーンショット保存ワークフロー: 生成した画像をArtifactsへアップロード
- name: Upload screenshots
  uses: actions/upload-artifact@v4
  with:
    # ブランチ名などから動的に決定したユニークなArtifact名
    name: ${{ steps.determine-artifact-name.outputs.artifact_name }}
    path: screenshots_output    # Roborazziが出力した画像フォルダ
    retention-days: 90          # 保存期間（90日）
    overwrite: true             # 同名Artifactがあれば上書き

# スクリーンショット比較ワークフロー: 前回保存した画像をArtifactsからダウンロード
- name: Download previous screenshots
  uses: dawidd6/action-download-artifact@v8
  id: download_artifact
  with:
    # PRのベースブランチに対応するArtifact名を指定
    name: ${{ steps.determine-artifact-name.outputs.artifact_name }}
    workflow: main.yml  # 画像を保存したワークフロー名（任意指定）
    search_artifacts: true                    # 上記nameに一致するArtifactを検索
    path: screenshots_output                  # ダウンロード先フォルダ